FROM ubuntu:25.04

RUN apt-get update \
    && apt-get install -y clang-format-18 \
    && ln -s /usr/bin/clang-format-18 /usr/local/bin/clang-format \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["clang-format"]
