#!/bin/bash

"@PYTHON_EXECUTABLE@" \
	"@GCF_SCRIPT@" \
	"--pre-commit" \
	"@GIT_EXECUTABLE@" \
	"@CLANG_FORMAT_BIN@" \
	"@DIFF_BIN@" \
	"@SED_BIN@" \
	"-style=@GCF_CLANGFORMAT_STYLE@" \
	"-ignore=@GCF_IGNORE_LIST@"
