# CMake generated Testfile for 
# Source directory: /home/mjs/src/GHEX/test/bindings/python
# Build directory: /home/mjs/src/GHEX/_nix_build/test/bindings/python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[py_context]=] "/home/mjs/src/GHEX/_nix_build/test_venv/bin/python" "-m" "pytest" "-s" "/home/mjs/src/GHEX/_nix_build/test/bindings/python/test_context.py")
set_tests_properties([=[py_context]=] PROPERTIES  LABELS "serial" RUN_SERIAL "ON" WORKING_DIRECTORY "/home/mjs/src/GHEX/_nix_build/bindings/python" _BACKTRACE_TRIPLES "/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;68;add_test;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;93;ghex_reg_pytest;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;0;")
add_test([=[py_context_parallel]=] "/nix/store/1gx7vrvkclgjc828hmxdscgcvhs5zi1k-python3-3.13.13-env/bin/mpiexec" "-n" "4" "/home/mjs/src/GHEX/_nix_build/test_venv/bin/python" "-m" "pytest" "-s" "--with-mpi" "/home/mjs/src/GHEX/_nix_build/test/bindings/python/test_context.py")
set_tests_properties([=[py_context_parallel]=] PROPERTIES  LABELS "parallel-ranks-4" RUN_SERIAL "ON" WORKING_DIRECTORY "/home/mjs/src/GHEX/_nix_build/bindings/python" _BACKTRACE_TRIPLES "/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;84;add_test;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;94;ghex_reg_parallel_pytest;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;0;")
add_test([=[py_structured_domain_descriptor_parallel]=] "/nix/store/1gx7vrvkclgjc828hmxdscgcvhs5zi1k-python3-3.13.13-env/bin/mpiexec" "-n" "4" "/home/mjs/src/GHEX/_nix_build/test_venv/bin/python" "-m" "pytest" "-s" "--with-mpi" "/home/mjs/src/GHEX/_nix_build/test/bindings/python/test_structured_domain_descriptor.py")
set_tests_properties([=[py_structured_domain_descriptor_parallel]=] PROPERTIES  LABELS "parallel-ranks-4" RUN_SERIAL "ON" WORKING_DIRECTORY "/home/mjs/src/GHEX/_nix_build/bindings/python" _BACKTRACE_TRIPLES "/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;84;add_test;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;96;ghex_reg_parallel_pytest;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;0;")
add_test([=[py_structured_pattern_parallel]=] "/nix/store/1gx7vrvkclgjc828hmxdscgcvhs5zi1k-python3-3.13.13-env/bin/mpiexec" "-n" "4" "/home/mjs/src/GHEX/_nix_build/test_venv/bin/python" "-m" "pytest" "-s" "--with-mpi" "/home/mjs/src/GHEX/_nix_build/test/bindings/python/test_structured_pattern.py")
set_tests_properties([=[py_structured_pattern_parallel]=] PROPERTIES  LABELS "parallel-ranks-4" RUN_SERIAL "ON" WORKING_DIRECTORY "/home/mjs/src/GHEX/_nix_build/bindings/python" _BACKTRACE_TRIPLES "/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;84;add_test;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;97;ghex_reg_parallel_pytest;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;0;")
add_test([=[py_unstructured_domain_descriptor_parallel]=] "/nix/store/1gx7vrvkclgjc828hmxdscgcvhs5zi1k-python3-3.13.13-env/bin/mpiexec" "-n" "4" "/home/mjs/src/GHEX/_nix_build/test_venv/bin/python" "-m" "pytest" "-s" "--with-mpi" "/home/mjs/src/GHEX/_nix_build/test/bindings/python/test_unstructured_domain_descriptor.py")
set_tests_properties([=[py_unstructured_domain_descriptor_parallel]=] PROPERTIES  LABELS "parallel-ranks-4" RUN_SERIAL "ON" WORKING_DIRECTORY "/home/mjs/src/GHEX/_nix_build/bindings/python" _BACKTRACE_TRIPLES "/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;84;add_test;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;100;ghex_reg_parallel_pytest;/home/mjs/src/GHEX/test/bindings/python/CMakeLists.txt;0;")
