function(make_version PREFIX VERSION_MAJOR VERSION_MINOR VERSION_PATCH)
    set(${PREFIX}_VERSION_MAJOR ${VERSION_MAJOR} PARENT_SCOPE)
    set(${PREFIX}_VERSION_MINOR ${VERSION_MINOR} PARENT_SCOPE)
    set(${PREFIX}_VERSION_PATCH ${VERSION_PATCH} PARENT_SCOPE)
    set(${PREFIX}_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}" PARENT_SCOPE)
    math(EXPR VN
        "${VERSION_PATCH} + 100*${VERSION_MINOR} + 10000*${VERSION_MAJOR}" OUTPUT_FORMAT DECIMAL) 
    set(${PREFIX}_VERSION_NUMERIC ${VN} PARENT_SCOPE)
endfunction()
