std::cout << "CMAKE_CXX_FLAGS=" << "" << std::endl;
std::cout << "CMAKE_C_FLAGS=" << "" << std::endl;
std::cout << "CMAKE_BUILD_TYPE=" << "Release" << std::endl;

std::cout << "OOMPH_UCX_USE_PMI=" << "" << std::endl;
std::cout << "OOMPH_UCX_USE_SPIN_LOCK=" << "" << std::endl;

std::cout << "HWLOC_INCLUDE_DIR=" << "" << std::endl;
std::cout << "HWLOC_LIBRARY=" << "" << std::endl;
std::cout << "UCP_INCLUDE_DIR=" << "" << std::endl;
std::cout << "UCP_LIBRARY=" << "" << std::endl;
std::cout << "XPMEM_INCLUDE_DIR=" << "" << std::endl;
std::cout << "XPMEM_LIBRARY=" << "" << std::endl;
